# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bearing_second.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import bearing_first
import sqlite3

conn = sqlite3.connect('bearing')
c = conn.cursor()

class Ui_second_window(object):
    def msg_normal(self, mess):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText(mess)
        msg.exec_()

    def insert_database(self):
        flag = 0
        new_id = self.txt_id2.toPlainText()
        new_name = self.txt_name2.toPlainText()
        c.execute("SELECT machine.ID from machine")
        data = c.fetchall()
        for i in data:
            if str(i[0]) == new_id:
                flag = 1
                break
        if new_id == "":
            self.msg_normal("Invalid Values")
        if flag == 1:
            self.msg_normal("Machine Already Exist")
            flag = 0
        elif flag == 0 and new_id != "":
            print("flag = 0")
            c.execute("INSERT INTO machine (ID, Name) VALUES (?, ?)", (new_id, new_name))
            conn.commit()
            self.msg_normal("Add Successfully")
    def closeWindow(self):
        self.window = QtWidgets.QWidget()
        self.ui = bearing_first.Ui_bearing()
        self.ui.setupUi(self.window)

    def setupUi(self, second_window):
        second_window.setObjectName("second_window")
        second_window.resize(629, 600)
        self.centralwidget = QtWidgets.QWidget(second_window)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_id2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_id2.setGeometry(QtCore.QRect(90, 60, 111, 31))
        self.lb_id2.setObjectName("lb_id2")
        self.lb_name2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_name2.setGeometry(QtCore.QRect(90, 100, 101, 31))
        self.lb_name2.setObjectName("lb_name2")
        self.txt_id2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_id2.setGeometry(QtCore.QRect(243, 60, 191, 31))
        self.txt_id2.setObjectName("txt_id2")
        self.txt_name2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name2.setGeometry(QtCore.QRect(243, 100, 191, 31))
        self.txt_name2.setObjectName("txt_name2")
        self.btn_done = QtWidgets.QPushButton(self.centralwidget)
        self.btn_done.setGeometry(QtCore.QRect(340, 150, 89, 25))
        self.btn_done.setObjectName("btn_done")
        second_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(second_window)
        self.statusbar.setObjectName("statusbar")
        second_window.setStatusBar(self.statusbar)

        self.btn_done.clicked.connect(self.insert_database)

        self.retranslateUi(second_window)
        QtCore.QMetaObject.connectSlotsByName(second_window)

    def retranslateUi(self, second_window):
        _translate = QtCore.QCoreApplication.translate
        second_window.setWindowTitle(_translate("second_window", "MACHINE INFOMATION"))
        self.lb_id2.setText(_translate("second_window", "Machine ID"))
        self.lb_name2.setText(_translate("second_window", "Machine Name"))
        self.btn_done.setText(_translate("second_window", "DONE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    second_window = QtWidgets.QMainWindow()
    ui = Ui_second_window()
    ui.setupUi(second_window)
    second_window.show()
    sys.exit(app.exec_())
